apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"ai-service","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ai-service"}},"template":{"metadata":{"labels":{"app":"ai-service"}},"spec":{"containers":[{"env":[{"name":"USE_AZURE_OPENAI","value":"False"},{"name":"GPT_SERVICE_URL","value":"http://gpt-service/generate"},{"name":"DALLE_SERVICE_URL","value":"http://dalle-service/generate-image"},{"name":"AZURE_OPENAI_API_VERSION","value":"2024-07-01-preview"},{"name":"AZURE_OPENAI_GPT_DEPLOYMENT_NAME","value":""},{"name":"AZURE_OPENAI_GPT_ENDPOINT","value":""},{"name":"AZURE_OPENAI_DALLE_ENDPOINT","value":""},{"name":"AZURE_OPENAI_DALLE_DEPLOYMENT_NAME","value":""},{"name":"OPENAI_GPT_API_KEY","valueFrom":{"secretKeyRef":{"key":"OPENAI_GPT_API_KEY","name":"openai-gpt-api-secret"}}},{"name":"OPENAI_DALLE_API_KEY","valueFrom":{"secretKeyRef":{"key":"OPENAI_DALLE_API_KEY","name":"openai-dalle-api-secret"}}}],"image":"gabriel1010/ai-service-l8:latest","livenessProbe":{"failureThreshold":10,"httpGet":{"path":"/health","port":5001},"initialDelaySeconds":3,"periodSeconds":10},"name":"ai-service","ports":[{"containerPort":5001}],"readinessProbe":{"failureThreshold":10,"httpGet":{"path":"/health","port":5001},"initialDelaySeconds":3,"periodSeconds":10},"resources":{"limits":{"cpu":"50m","memory":"128Mi"},"requests":{"cpu":"20m","memory":"50Mi"}},"startupProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":5001},"initialDelaySeconds":60,"periodSeconds":5}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2025-12-11T02:33:11Z"
  generation: 3
  name: ai-service
  namespace: default
  resourceVersion: "25136"
  uid: 9a37313f-2bb9-4abc-bd8f-f5b8b4b834b7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ai-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-11T03:21:27Z"
      creationTimestamp: null
      labels:
        app: ai-service
    spec:
      containers:
      - env:
        - name: USE_AZURE_OPENAI
          value: "False"
        - name: GPT_SERVICE_URL
          value: http://gpt-service/generate
        - name: DALLE_SERVICE_URL
          value: http://dalle-service/generate-image
        - name: AZURE_OPENAI_API_VERSION
          value: 2024-07-01-preview
        - name: AZURE_OPENAI_GPT_DEPLOYMENT_NAME
        - name: AZURE_OPENAI_GPT_ENDPOINT
        - name: AZURE_OPENAI_DALLE_ENDPOINT
        - name: AZURE_OPENAI_DALLE_DEPLOYMENT_NAME
        - name: OPENAI_GPT_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_GPT_API_KEY
              name: openai-gpt-api-secret
        - name: OPENAI_DALLE_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_DALLE_API_KEY
              name: openai-dalle-api-secret
        image: gabriel1010/ai-service-l9:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 5001
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ai-service
        ports:
        - containerPort: 5001
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 5001
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 50Mi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5001
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-11T02:35:26Z"
    lastUpdateTime: "2025-12-11T02:35:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-11T02:33:11Z"
    lastUpdateTime: "2025-12-11T03:23:08Z"
    message: ReplicaSet "ai-service-78584ccb5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ai-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":5001,"targetPort":5001}],"selector":{"app":"ai-service"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-11T02:33:11Z"
  name: ai-service
  namespace: default
  resourceVersion: "10408"
  uid: ed0167d0-c41b-4966-8fac-38ba5ffad29f
spec:
  clusterIP: 10.0.30.207
  clusterIPs:
  - 10.0.30.207
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: ai-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
