apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"dalle-service","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"dalle-service"}},"template":{"metadata":{"labels":{"app":"dalle-service"}},"spec":{"containers":[{"env":[{"name":"OPENAI_API_KEY","valueFrom":{"secretKeyRef":{"key":"OPENAI_DALLE_API_KEY","name":"openai-dalle-api-secret"}}}],"image":"gabriel1010/dall-e-service-l8:test","name":"dalle-service","ports":[{"containerPort":8000}],"resources":{"limits":{"cpu":"50m","memory":"128Mi"},"requests":{"cpu":"20m","memory":"50Mi"}}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2025-12-11T02:33:10Z"
  generation: 3
  name: dalle-service
  namespace: default
  resourceVersion: "24431"
  uid: d6cc63e0-a522-4f1d-b665-38c1d10f359f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dalle-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-11T03:20:27Z"
      creationTimestamp: null
      labels:
        app: dalle-service
    spec:
      containers:
      - env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_DALLE_API_KEY
              name: openai-dalle-api-secret
        image: gabriel1010/dall-e-service-l9:latest
        imagePullPolicy: IfNotPresent
        name: dalle-service
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-11T02:34:27Z"
    lastUpdateTime: "2025-12-11T02:34:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-11T02:33:10Z"
    lastUpdateTime: "2025-12-11T03:21:11Z"
    message: ReplicaSet "dalle-service-576d557578" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"dalle-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8000}],"selector":{"app":"dalle-service"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-11T02:33:11Z"
  name: dalle-service
  namespace: default
  resourceVersion: "10390"
  uid: 93a8a691-bef6-4024-8800-11f089a2cbc2
spec:
  clusterIP: 10.0.103.113
  clusterIPs:
  - 10.0.103.113
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: dalle-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
