apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"gpt-service","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"gpt-service"}},"template":{"metadata":{"labels":{"app":"gpt-service"}},"spec":{"containers":[{"env":[{"name":"OPENAI_API_KEY","valueFrom":{"secretKeyRef":{"key":"OPENAI_GPT_API_KEY","name":"openai-gpt-api-secret"}}}],"image":"gabriel1010/gpt-service-l8:test","name":"gpt-service","ports":[{"containerPort":8000}],"resources":{"limits":{"cpu":"50m","memory":"128Mi"},"requests":{"cpu":"20m","memory":"50Mi"}}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2025-12-11T02:33:10Z"
  generation: 3
  name: gpt-service
  namespace: default
  resourceVersion: "24406"
  uid: 1b55e8f8-89ed-48fd-b803-c31efbd11bb0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gpt-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-11T03:20:20Z"
      creationTimestamp: null
      labels:
        app: gpt-service
    spec:
      containers:
      - env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_GPT_API_KEY
              name: openai-gpt-api-secret
        image: gabriel1010/gpt-service-l9:latest
        imagePullPolicy: IfNotPresent
        name: gpt-service
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-11T02:34:28Z"
    lastUpdateTime: "2025-12-11T02:34:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-11T02:33:10Z"
    lastUpdateTime: "2025-12-11T03:21:10Z"
    message: ReplicaSet "gpt-service-6f4cf44c9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"gpt-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8000}],"selector":{"app":"gpt-service"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-11T02:33:10Z"
  name: gpt-service
  namespace: default
  resourceVersion: "10368"
  uid: 22f24395-5afe-4bee-ba80-9910e5b9c67c
spec:
  clusterIP: 10.0.240.206
  clusterIPs:
  - 10.0.240.206
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: gpt-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
