apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"order-service","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"order-service"}},"template":{"metadata":{"labels":{"app":"order-service"}},"spec":{"containers":[{"env":[{"name":"ORDER_QUEUE_HOSTNAME","value":"rabbitmq"},{"name":"ORDER_QUEUE_PORT","value":"5672"},{"name":"ORDER_QUEUE_USERNAME","value":"username"},{"name":"ORDER_QUEUE_PASSWORD","value":"password"},{"name":"ORDER_QUEUE_NAME","value":"orders"},{"name":"FASTIFY_ADDRESS","value":"0.0.0.0"}],"image":"gabriel1010/order-service-l8:latest","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":3,"periodSeconds":3},"name":"order-service","ports":[{"containerPort":3000}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":3,"periodSeconds":5},"resources":{"limits":{"cpu":"100m","memory":"256Mi"},"requests":{"cpu":"1m","memory":"50Mi"}},"startupProbe":{"failureThreshold":5,"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":20,"periodSeconds":10}}],"initContainers":[{"command":["sh","-c","until nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;"],"image":"busybox","name":"wait-for-rabbitmq","resources":{"limits":{"cpu":"100m","memory":"256Mi"},"requests":{"cpu":"1m","memory":"50Mi"}}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2025-12-11T02:33:08Z"
  generation: 3
  name: order-service
  namespace: default
  resourceVersion: "24485"
  uid: 64a88d8b-5b88-4d02-b418-4b744e49f073
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: order-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-11T03:20:16Z"
      creationTimestamp: null
      labels:
        app: order-service
    spec:
      containers:
      - env:
        - name: ORDER_QUEUE_HOSTNAME
          value: rabbitmq
        - name: ORDER_QUEUE_PORT
          value: "5672"
        - name: ORDER_QUEUE_USERNAME
          value: username
        - name: ORDER_QUEUE_PASSWORD
          value: password
        - name: ORDER_QUEUE_NAME
          value: orders
        - name: FASTIFY_ADDRESS
          value: 0.0.0.0
        image: gabriel1010/order-service-l9:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: order-service
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 1m
            memory: 50Mi
        startupProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;
        image: busybox
        imagePullPolicy: Always
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 1m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-11T02:37:09Z"
    lastUpdateTime: "2025-12-11T02:37:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-11T02:33:08Z"
    lastUpdateTime: "2025-12-11T03:21:17Z"
    message: ReplicaSet "order-service-6c8c69fc85" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"order-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":3000,"targetPort":3000}],"selector":{"app":"order-service"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-11T02:33:08Z"
  name: order-service
  namespace: default
  resourceVersion: "10240"
  uid: 63160805-97e3-433f-80e4-8ecb3b6eb3cc
spec:
  clusterIP: 10.0.219.218
  clusterIPs:
  - 10.0.219.218
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: order-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
