apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"store-admin","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"store-admin"}},"template":{"metadata":{"labels":{"app":"store-admin"}},"spec":{"containers":[{"env":[{"name":"VUE_APP_PRODUCT_SERVICE_URL","value":"http://product-service:3002/"},{"name":"VUE_APP_MAKELINE_SERVICE_URL","value":"http://makeline-service:3001/"}],"image":"gabriel1010/store-admin-l8:latest","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/health","port":8081},"initialDelaySeconds":3,"periodSeconds":3},"name":"store-admin","ports":[{"containerPort":8081,"name":"store-admin"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8081},"initialDelaySeconds":3,"periodSeconds":5},"resources":{"limits":{"cpu":"1000m","memory":"512Mi"},"requests":{"cpu":"1m","memory":"200Mi"}},"startupProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8081},"initialDelaySeconds":5,"periodSeconds":5}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2025-12-11T02:33:10Z"
  generation: 3
  name: store-admin
  namespace: default
  resourceVersion: "24195"
  uid: e0f702d2-8683-4094-8b79-713d7cc99762
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: store-admin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-11T03:20:26Z"
      creationTimestamp: null
      labels:
        app: store-admin
    spec:
      containers:
      - env:
        - name: VUE_APP_PRODUCT_SERVICE_URL
          value: http://product-service:3002/
        - name: VUE_APP_MAKELINE_SERVICE_URL
          value: http://makeline-service:3001/
        image: gabriel1010/store-admin-l9:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: store-admin
        ports:
        - containerPort: 8081
          name: store-admin
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 1m
            memory: 200Mi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-11T02:33:30Z"
    lastUpdateTime: "2025-12-11T02:33:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-11T02:33:10Z"
    lastUpdateTime: "2025-12-11T03:20:46Z"
    message: ReplicaSet "store-admin-6d6587fb87" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"store-admin","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":8081}],"selector":{"app":"store-admin"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-12-11T02:33:10Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: store-admin
  namespace: default
  resourceVersion: "10550"
  uid: 1455c4c5-75ef-440d-a65f-7e2d2e73e757
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.54.63
  clusterIPs:
  - 10.0.54.63
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30432
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: store-admin
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.185.26.83
      ipMode: VIP
