apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"store-front","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"store-front"}},"template":{"metadata":{"labels":{"app":"store-front"}},"spec":{"containers":[{"env":[{"name":"VUE_APP_ORDER_SERVICE_URL","value":"http://order-service:3000/"},{"name":"VUE_APP_PRODUCT_SERVICE_URL","value":"http://product-service:3002/"}],"image":"gabriel1010/store-front-l8:latest","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":3,"periodSeconds":3},"name":"store-front","ports":[{"containerPort":8080,"name":"store-front"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":3,"periodSeconds":3},"resources":{"limits":{"cpu":"1000m","memory":"512Mi"},"requests":{"cpu":"1m","memory":"200Mi"}},"startupProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":5,"periodSeconds":5}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2025-12-11T02:33:09Z"
  generation: 4
  name: store-front
  namespace: default
  resourceVersion: "24344"
  uid: e0592da2-69b0-4ae4-98ab-f0d5abe03bb6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: store-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-11T03:20:44Z"
      creationTimestamp: null
      labels:
        app: store-front
    spec:
      containers:
      - env:
        - name: VUE_APP_ORDER_SERVICE_URL
          value: http://order-service:3000/
        - name: VUE_APP_PRODUCT_SERVICE_URL
          value: http://product-service:3002/
        image: gabriel1010/store-front-final:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: store-front
        ports:
        - containerPort: 8080
          name: store-front
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 1m
            memory: 200Mi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-11T02:33:25Z"
    lastUpdateTime: "2025-12-11T02:33:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-11T02:33:09Z"
    lastUpdateTime: "2025-12-11T03:21:04Z"
    message: ReplicaSet "store-front-59bb96b5cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"store-front","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"app":"store-front"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-12-11T02:33:09Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: store-front
  namespace: default
  resourceVersion: "10476"
  uid: f834ab18-26e3-4e39-8ced-981f754a365a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.160.64
  clusterIPs:
  - 10.0.160.64
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30422
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: store-front
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.253.212.99
      ipMode: VIP
