apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"virtual-worker","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"virtual-worker"}},"template":{"metadata":{"labels":{"app":"virtual-worker"}},"spec":{"containers":[{"env":[{"name":"MAKELINE_SERVICE_URL","value":"http://makeline-service:3001"},{"name":"ORDERS_PER_HOUR","value":"50"}],"image":"gabriel1010/virtual-worker-l8:latest","name":"virtual-worker","resources":{"limits":{"cpu":"2m","memory":"20Mi"},"requests":{"cpu":"1m","memory":"1Mi"}}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2025-12-11T02:33:47Z"
  generation: 3
  name: virtual-worker
  namespace: default
  resourceVersion: "24240"
  uid: 472f0bff-bc69-4fb2-87ec-e17b32069728
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: virtual-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-11T03:20:32Z"
      creationTimestamp: null
      labels:
        app: virtual-worker
    spec:
      containers:
      - env:
        - name: MAKELINE_SERVICE_URL
          value: http://makeline-service:3001
        - name: ORDERS_PER_HOUR
          value: "50"
        image: gabriel1010/virtual-worker-l9:latest
        imagePullPolicy: Always
        name: virtual-worker
        resources:
          limits:
            cpu: 2m
            memory: 20Mi
          requests:
            cpu: 1m
            memory: 1Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-11T02:34:10Z"
    lastUpdateTime: "2025-12-11T02:34:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-11T02:33:47Z"
    lastUpdateTime: "2025-12-11T03:20:52Z"
    message: ReplicaSet "virtual-worker-7f5b69699d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
