apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"virtual-customer","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"virtual-customer"}},"template":{"metadata":{"labels":{"app":"virtual-customer"}},"spec":{"containers":[{"env":[{"name":"ORDER_SERVICE_URL","value":"http://order-service:3000/"},{"name":"ORDERS_PER_HOUR","value":"200"}],"image":"gabriel1010/virtual-customer-l8:latest","name":"virtual-customer","resources":{"limits":{"cpu":"2m","memory":"20Mi"},"requests":{"cpu":"1m","memory":"1Mi"}}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2025-12-11T02:33:47Z"
  generation: 3
  name: virtual-customer
  namespace: default
  resourceVersion: "24261"
  uid: 05107772-5721-4f6b-8d8e-d9bc5e8e85bb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: virtual-customer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-11T03:20:35Z"
      creationTimestamp: null
      labels:
        app: virtual-customer
    spec:
      containers:
      - env:
        - name: ORDER_SERVICE_URL
          value: http://order-service:3000/
        - name: ORDERS_PER_HOUR
          value: "200"
        image: gabriel1010/virtual-customer-l9:latest
        imagePullPolicy: Always
        name: virtual-customer
        resources:
          limits:
            cpu: 2m
            memory: 20Mi
          requests:
            cpu: 1m
            memory: 1Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-11T02:34:11Z"
    lastUpdateTime: "2025-12-11T02:34:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-11T02:33:47Z"
    lastUpdateTime: "2025-12-11T03:20:53Z"
    message: ReplicaSet "virtual-customer-856d6b49bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
